### ISSUE TITLE
Barcode Scanner High Sensitivity

### ISSUE THREAD

**Issue by Mr6060** [Davoleo/BarcodeStock#2]
The barcode scanner is too quick, takes whatever he wants from the zone he analyzes. Even plain text.

**Comment by Davoleo** [comment]
blame the lib, bitch

**Comment by Mr6060** [comment]
Use another lib bitch

**Comment by Davoleo** [comment]
Hopefully filtering out some formats decreases the sensitivity

**Comment by Mr6060** [comment]
I don't think that's how it works but ok

**Comment by Davoleo** [comment]
_shut up_
