### ISSUE TITLE
Search features

### ISSUE THREAD

**Issue by Mr6060** [Davoleo/BarcodeStock#3]
The search happens in both title and description, it's kind of unsettling, I've spent 5 minutes figuring out why writing a title gives me other products as well, should have maybe search by description or title, maybe a setting page where I can choose how to customize for my use

**Comment by Davoleo** [comment]
to be honest that's how most of search engines work

**Comment by Mr6060** [comment]
Still, I would prefer some degree of customization, to get the app to work as I want it to work

**Comment by Davoleo** [comment]
Search Settings:
- [ ] Search included fields
- [ ] Case Sensitive/Insensitive
