### ISSUE TITLE
Automatically Barcode Filter by Scan

### ISSUE THREAD

**Issue by Mr6060** [Davoleo/BarcodeStock#4]
Now I've used the handy barcode "search" on one of my products, which was already saved, the app didn't look for it and just let me add the same barcode twice, now you should understand why that's crap

**Comment by Davoleo** [comment]
didn't it come up when you pressed "Search" in the dialog box?

**Comment by Mr6060** [comment]
1) ok, there is the search button, didn't see it
2) there should not be a search button, the search should be automatic and then if there is no barcode the option to add it
3) Still, that let's me use the same barcode which is wrong

**Comment by Davoleo** [comment]
ok boomer
